version: '3.9'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    env_file:
      - ./backend/.env
    depends_on: 
      - api
