From python:3.11-slim

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root
COPY app/ app/

COPY worker/ worker/

CMD ["poetry" ,"run", "python", "worker/job_worker.py"]