name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
      ECR_API_REPO: 256595875099.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/job-queue-api
      ECR_WORKER_REPO: 256595875099.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/job-queue-worker


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install --no-root
      
      - name : Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

        
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 256595875099.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com


      - name: Build and push API Docker Image
        working-directory: ./backend
        run: |
          docker build -f Dockerfile -t job-queue-api .
          docker tag job-queue-api:latest $ECR_API_REPO:latest
          docker push $ECR_API_REPO:latest

      - name: Build and push worker Docker Image
        working-directory: ./backend
        run: |
          docker build -f Dockerfile.worker -t job-queue-worker .
          docker tag job-queue-worker:latest $ECR_WORKER_REPO:latest
          docker push $ECR_WORKER_REPO:latest